/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Flavour } from "./components/v-map/map-provider/provider-factory";
import { MapProviderDetail } from "./utils/events";
import { LayerConfig, MapProvider, StyleConfig } from "./components/v-map/map-provider/map-provider";
export { Flavour } from "./components/v-map/map-provider/provider-factory";
export { MapProviderDetail } from "./utils/events";
export { LayerConfig, MapProvider, StyleConfig } from "./components/v-map/map-provider/map-provider";
export namespace Components {
    interface VMap {
        "addLayer": (layerConfig: any) => Promise<void>;
        /**
          * @default '0,0'
         */
        "center": string;
        /**
          * @default 'ol'
         */
        "flavour": Flavour;
        "getMapProvider": () => Promise<MapProvider>;
        "isMapProviderAvailable": () => Promise<boolean>;
        "setView": (coordinates: [number, number], zoom: number) => Promise<void>;
        /**
          * Falls true, injiziert v-map automatisch die Import-Map.
          * @default true
         */
        "useDefaultImportMap": boolean;
        /**
          * @default 2
         */
        "zoom": number;
    }
    interface VMapLayerGeojson {
        "addToMap": (mapElement: HTMLVMapElement) => Promise<void>;
        /**
          * @default 1.0
         */
        "opacity": number;
        "url": string;
        "vectorStyle"?: StyleConfig;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible": boolean;
    }
    interface VMapLayerGroup {
        "addLayer": (layerConfig: LayerConfig) => Promise<void>;
        /**
          * @default false
         */
        "basemap": boolean;
        /**
          * @default Math.random().toString(36).slice(2, 11)
         */
        "groupId": string;
        /**
          * @default 1.0
         */
        "opacity": number;
        /**
          * @default true
         */
        "visible": boolean;
    }
    interface VMapLayerOsm {
        "addToMap": (mapElement: HTMLVMapElement) => Promise<void>;
        /**
          * @default 1.0
         */
        "opacity": number;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible": boolean;
    }
}
export interface VMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapElement;
}
export interface VMapLayerOsmCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerOsmElement;
}
declare global {
    interface HTMLVMapElementEventMap {
        "mapProviderReady": MapProviderDetail;
    }
    interface HTMLVMapElement extends Components.VMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapElementEventMap>(type: K, listener: (this: HTMLVMapElement, ev: VMapCustomEvent<HTMLVMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapElementEventMap>(type: K, listener: (this: HTMLVMapElement, ev: VMapCustomEvent<HTMLVMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapElement: {
        prototype: HTMLVMapElement;
        new (): HTMLVMapElement;
    };
    interface HTMLVMapLayerGeojsonElement extends Components.VMapLayerGeojson, HTMLStencilElement {
    }
    var HTMLVMapLayerGeojsonElement: {
        prototype: HTMLVMapLayerGeojsonElement;
        new (): HTMLVMapLayerGeojsonElement;
    };
    interface HTMLVMapLayerGroupElement extends Components.VMapLayerGroup, HTMLStencilElement {
    }
    var HTMLVMapLayerGroupElement: {
        prototype: HTMLVMapLayerGroupElement;
        new (): HTMLVMapLayerGroupElement;
    };
    interface HTMLVMapLayerOsmElementEventMap {
        "ready": void;
    }
    interface HTMLVMapLayerOsmElement extends Components.VMapLayerOsm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerOsmElementEventMap>(type: K, listener: (this: HTMLVMapLayerOsmElement, ev: VMapLayerOsmCustomEvent<HTMLVMapLayerOsmElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerOsmElementEventMap>(type: K, listener: (this: HTMLVMapLayerOsmElement, ev: VMapLayerOsmCustomEvent<HTMLVMapLayerOsmElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerOsmElement: {
        prototype: HTMLVMapLayerOsmElement;
        new (): HTMLVMapLayerOsmElement;
    };
    interface HTMLElementTagNameMap {
        "v-map": HTMLVMapElement;
        "v-map-layer-geojson": HTMLVMapLayerGeojsonElement;
        "v-map-layer-group": HTMLVMapLayerGroupElement;
        "v-map-layer-osm": HTMLVMapLayerOsmElement;
    }
}
declare namespace LocalJSX {
    interface VMap {
        /**
          * @default '0,0'
         */
        "center"?: string;
        /**
          * @default 'ol'
         */
        "flavour"?: Flavour;
        "onMapProviderReady"?: (event: VMapCustomEvent<MapProviderDetail>) => void;
        /**
          * Falls true, injiziert v-map automatisch die Import-Map.
          * @default true
         */
        "useDefaultImportMap"?: boolean;
        /**
          * @default 2
         */
        "zoom"?: number;
    }
    interface VMapLayerGeojson {
        /**
          * @default 1.0
         */
        "opacity"?: number;
        "url"?: string;
        "vectorStyle"?: StyleConfig;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible"?: boolean;
    }
    interface VMapLayerGroup {
        /**
          * @default false
         */
        "basemap"?: boolean;
        /**
          * @default Math.random().toString(36).slice(2, 11)
         */
        "groupId"?: string;
        /**
          * @default 1.0
         */
        "opacity"?: number;
        /**
          * @default true
         */
        "visible"?: boolean;
    }
    interface VMapLayerOsm {
        "onReady"?: (event: VMapLayerOsmCustomEvent<void>) => void;
        /**
          * @default 1.0
         */
        "opacity"?: number;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "v-map": VMap;
        "v-map-layer-geojson": VMapLayerGeojson;
        "v-map-layer-group": VMapLayerGroup;
        "v-map-layer-osm": VMapLayerOsm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v-map": LocalJSX.VMap & JSXBase.HTMLAttributes<HTMLVMapElement>;
            "v-map-layer-geojson": LocalJSX.VMapLayerGeojson & JSXBase.HTMLAttributes<HTMLVMapLayerGeojsonElement>;
            "v-map-layer-group": LocalJSX.VMapLayerGroup & JSXBase.HTMLAttributes<HTMLVMapLayerGroupElement>;
            "v-map-layer-osm": LocalJSX.VMapLayerOsm & JSXBase.HTMLAttributes<HTMLVMapLayerOsmElement>;
        }
    }
}
