/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Flavour } from "./types/flavour";
import { CssMode } from "./types/cssmode";
import { MapProviderDetail } from "./utils/events";
import { MapProvider } from "./types/mapprovider";
import { BuilderConfig } from "./utils/diff";
import { Color } from "./components/v-map-layer-scatterplot/v-map-layer-scatterplot";
import { LayerConfig } from "./types/layerconfig";
import { ResolvedStyle, StyleFormat } from "./components/v-map-style/v-map-style";
export { Flavour } from "./types/flavour";
export { CssMode } from "./types/cssmode";
export { MapProviderDetail } from "./utils/events";
export { MapProvider } from "./types/mapprovider";
export { BuilderConfig } from "./utils/diff";
export { Color } from "./components/v-map-layer-scatterplot/v-map-layer-scatterplot";
export { LayerConfig } from "./types/layerconfig";
export { ResolvedStyle, StyleFormat } from "./components/v-map-style/v-map-style";
export namespace Components {
    interface VMap {
        /**
          * Mittelpunkt der Karte im **WGS84**-Koordinatensystem. Erwartet [lon, lat] (Längengrad, Breitengrad).
          * @default [0, 0]
          * @example <v-map center="[11.5761, 48.1371]" zoom="12"></v-map>
         */
        "center": string;
        /**
          * Aktiviert ein „CSS-Only“-Rendering (z. B. für einfache Tests/Layouts). Bei `true` werden keine Provider initialisiert.
          * @default false
         */
        "cssMode": CssMode;
        /**
          * Zu verwendender Karten-Provider. Unterstützte Werte: "ol" | "leaflet" | "cesium" | "deck".
          * @default "ol"
          * @example <v-map flavour="leaflet"></v-map>
         */
        "flavour": Flavour;
        /**
          * Liefert die aktive Provider-Instanz (z. B. OL-, Leaflet- oder Deck-Wrapper). Nützlich für fortgeschrittene Integrationen.
          * @returns Promise mit der Provider-Instanz oder `undefined`, falls noch nicht bereit.
         */
        "getMapProvider": () => Promise<MapProvider>;
        /**
          * Prüft, ob ein bestimmter Provider im aktuellen Build/Runtime verfügbar ist.
          * @param flavour Gewünschter Provider (optional; Standard ist `this.flavour`)
          * @returns `true`, wenn verfügbar, sonst `false`.
         */
        "isMapProviderAvailable": () => Promise<boolean>;
        /**
          * Setzt Kartenzentrum und Zoom (optional animiert).
          * @param center [lon, lat] in WGS84
          * @param zoom Zoomstufe
          * @param options Zusätzliche Optionen (z. B. { animate: true, duration: 300 })
          * @example await mapEl.setView([7.1, 50.7], 10, { animate: true, duration: 400 });
         */
        "setView": (coordinates: [number, number], zoom: number) => Promise<void>;
        /**
          * Falls true, injiziert v-map automatisch die Import-Map.
          * @default true
         */
        "useDefaultImportMap": boolean;
        /**
          * Anfangs-Zoomstufe. Skala abhängig vom Provider (typisch 0–20).
          * @default 3
         */
        "zoom": number;
    }
    /**
     * A component that builds map configurations dynamically from JSON/YAML configuration scripts.
     */
    interface VMapBuilder {
        /**
          * Configuration object for the map builder. Can be any structure that will be normalized to BuilderConfig.
         */
        "mapconfig"?: unknown;
    }
    interface VMapLayerGeojson {
        /**
          * Fill color for polygon geometries (CSS color value)
          * @default 'rgba(0,100,255,0.3)'
         */
        "fillColor"?: string;
        /**
          * Fill opacity for polygon geometries (0-1)
          * @default 0.3
         */
        "fillOpacity"?: number;
        /**
          * Prop, die du intern nutzt/weiterverarbeitest
         */
        "geojson"?: unknown;
        /**
          * Returns the internal layer ID used by the map provider.
         */
        "getLayerId": () => Promise<string>;
        /**
          * Icon size as [width, height] in pixels (comma-separated string like "32,32")
          * @default "32,32"
         */
        "iconSize"?: string;
        /**
          * Icon URL for point features (alternative to pointColor/pointRadius)
         */
        "iconUrl"?: string;
        /**
          * Opazität der geojson-Kacheln (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Point color for point geometries (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "pointColor"?: string;
        /**
          * Point radius for point geometries in pixels
          * @default 6
         */
        "pointRadius"?: number;
        /**
          * Stroke color for lines and polygon outlines (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "strokeColor"?: string;
        /**
          * Stroke opacity (0-1)
          * @default 1
         */
        "strokeOpacity"?: number;
        /**
          * Stroke width in pixels
          * @default 2
         */
        "strokeWidth"?: number;
        /**
          * Text color for labels (CSS color value)
          * @default '#000000'
         */
        "textColor"?: string;
        /**
          * Text property name from feature properties to display as label
         */
        "textProperty"?: string;
        /**
          * Text size for labels in pixels
          * @default 12
         */
        "textSize"?: number;
        /**
          * URL to fetch GeoJSON data from. Alternative to providing data via slot.
          * @default null
         */
        "url": string;
        /**
          * Whether the layer is visible on the map.
          * @default true
         */
        "visible": boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 1000
         */
        "zIndex": number;
    }
    interface VMapLayerGeotiff {
        /**
          * Returns the internal layer ID used by the map provider.
         */
        "getLayerId": () => Promise<string>;
        /**
          * Opazität der GeoTIFF-Kacheln (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * URL to the GeoTIFF file to be displayed on the map.
          * @default null
         */
        "url": string;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible": boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 1000
         */
        "zIndex": number;
    }
    /**
     * Google Maps Basemap Layer
     */
    interface VMapLayerGoogle {
        /**
          * Google Maps API-Schlüssel.
          * @example <v-map-layer-google api-key="YOUR_KEY"></v-map-layer-google>
         */
        "apiKey"?: string;
        /**
          * Sprach-Lokalisierung (BCP-47, z. B. "de", "en-US").
          * @default "en"
         */
        "language"?: string;
        /**
          * Google Maps libraries to load (comma-separated string).
          * @example "geometry,places,drawing"
         */
        "libraries"?: string;
        /**
          * Karten-Typ: "roadmap" | "satellite" | "hybrid" | "terrain".
          * @default "roadmap"
         */
        "mapType": | 'roadmap'
    | 'satellite'
    | 'terrain'
    | 'hybrid';
        /**
          * Maximum zoom level for the layer.
         */
        "maxZoom"?: number;
        /**
          * Opazität des Layers (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Region-Bias (ccTLD/Region-Code, z. B. "DE", "US"). Beeinflusst Labels/Suchergebnisse.
         */
        "region"?: string;
        /**
          * Scale factor for tile display.
          * @default "scaleFactor1x"
         */
        "scale"?: 'scaleFactor1x' | 'scaleFactor2x' | 'scaleFactor4x';
        /**
          * Custom styles for the Google Map (JSON array of styling objects). Can be passed as JSON string or array.
         */
        "styles"?: any[] | string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible": boolean;
    }
    interface VMapLayerOsm {
        /**
          * Returns the internal layer ID used by the map provider.
         */
        "getLayerId": () => Promise<string>;
        /**
          * Opazität der OSM-Kacheln (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Base URL for OpenStreetMap tile server. Defaults to the standard OSM tile server.
          * @default 'https://tile.openstreetmap.org'
         */
        "url": string;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible": boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 10
         */
        "zIndex": number;
    }
    interface VMapLayerScatterplot {
        /**
          * Datenquelle für Punkte. Erwartet Objekte mit mindestens einer Position in [lon, lat]. Zusätzliche Felder sind erlaubt.
         */
        "data"?: string;
        /**
          * Funktion zur Bestimmung der Füllfarbe je Punkt. Rückgabe z. B. [r,g,b] oder CSS-Farbe (providerabhängig).
          * @default '#3388ff'
         */
        "getFillColor": Color;
        /**
          * Funktion/konstanter Wert für den Punkt-Radius.
          * @default 4
         */
        "getRadius": number;
        /**
          * Globale Opazität (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Optionaler Remote-Pfad für JSON/CSV/GeoJSON, der zu `data` geladen wird.
         */
        "url"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible": boolean;
    }
    interface VMapLayerTerrain {
        /**
          * Basisfarbe für das Terrain. Erwartet Hex oder RGB (z. B. '#ff0000' oder '255,0,0').
         */
        "color"?: string;
        /**
          * URL zu Höhenraster im Heightmap-Format (z. B. GeoTIFF oder PNG Heightmap).
         */
        "elevationData": string;
        /**
          * JSON-Repräsentation eines Elevation-Decoders (z. B. '{"r":1,"g":1,"b":1,"offset":0}').
         */
        "elevationDecoder"?: string;
        /**
          * Liefert `true`, sobald das Terrain-Layer initialisiert wurde.
         */
        "isReady": () => Promise<boolean>;
        /**
          * Maximale Zoomstufe für das Terrain.
         */
        "maxZoom"?: number;
        /**
          * Fehler-Toleranz für das Mesh (wird an TerrainRenderer durchgereicht).
         */
        "meshMaxError"?: number;
        /**
          * Minimale Zoomstufe für das Terrain.
         */
        "minZoom"?: number;
        /**
          * Opazität des Layers.
          * @default 1
         */
        "opacity": number;
        /**
          * Optionale Textur (RGB) für das Terrain.
         */
        "texture"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible": boolean;
        /**
          * Darstellung des Mesh als Drahtgitter.
         */
        "wireframe"?: boolean;
        /**
          * Z-Index für die Darstellung.
          * @default 1000
         */
        "zIndex": number;
    }
    interface VMapLayerTile3d {
        /**
          * Indicates whether the tileset has been initialised and added to the map.
         */
        "isReady": () => Promise<boolean>;
        /**
          * Global opacity factor (0-1).
          * @default 1
         */
        "opacity": number;
        /**
          * Optional JSON string or object with Cesium3DTileset options.
         */
        "tilesetOptions"?: string | Record<string, unknown>;
        /**
          * URL pointing to the Cesium 3D Tileset.
         */
        "url": string;
        /**
          * Whether the tileset should be visible.
          * @default true
         */
        "visible": boolean;
        /**
          * Z-index used for ordering tilesets.
          * @default 1000
         */
        "zIndex": number;
    }
    interface VMapLayerWcs {
        /**
          * Coverage-Name/ID.
         */
        "coverageName": string;
        /**
          * Ausgabeformat, z. B. image/tiff.
          * @default 'image/tiff'
         */
        "format": string;
        /**
          * Gibt `true` zurück, sobald der Layer initialisiert wurde.
         */
        "isReady": () => Promise<boolean>;
        /**
          * Opazität (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Zusätzliche Parameter als JSON-String.
         */
        "params"?: string;
        /**
          * Projektion (Projection) für die Quelle.
         */
        "projection"?: string;
        /**
          * Auflösungen als JSON-Array, z. B. [1000,500].
         */
        "resolutions"?: string;
        /**
          * Basis-URL des WCS-Dienstes.
         */
        "url": string;
        /**
          * WCS-Version.
          * @default '1.1.0'
         */
        "version": string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible": boolean;
        /**
          * Z-Index für die Darstellung.
          * @default 1000
         */
        "zIndex": number;
    }
    interface VMapLayerWfs {
        /**
          * Gibt `true` zurück, sobald der Layer initialisiert wurde.
         */
        "isReady": () => Promise<boolean>;
        /**
          * Opazität (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Ausgabeformat, z. B. application/json.
          * @default 'application/json'
         */
        "outputFormat": string;
        /**
          * Zusätzliche Parameter als JSON-String.
         */
        "params"?: string;
        /**
          * Ziel-Referenzsystem, Standard EPSG:3857.
          * @default 'EPSG:3857'
         */
        "srsName": string;
        /**
          * Feature-Typ (typeName) des WFS.
         */
        "typeName": string;
        /**
          * WFS Endpunkt (z. B. https://server/wfs).
         */
        "url": string;
        /**
          * WFS Version, Standard 1.1.0.
          * @default '1.1.0'
         */
        "version": string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible": boolean;
        /**
          * Z-Index für Rendering.
          * @default 1000
         */
        "zIndex": number;
    }
    interface VMapLayerWkt {
        /**
          * Fill color for polygon geometries (CSS color value)
          * @default 'rgba(0,100,255,0.3)'
         */
        "fillColor"?: string;
        /**
          * Fill opacity for polygon geometries (0-1)
          * @default 0.3
         */
        "fillOpacity"?: number;
        /**
          * Returns the internal layer ID used by the map provider.
         */
        "getLayerId": () => Promise<string>;
        /**
          * Icon size as [width, height] in pixels (comma-separated string like "32,32")
          * @default "32,32"
         */
        "iconSize"?: string;
        /**
          * Icon URL for point features (alternative to pointColor/pointRadius)
         */
        "iconUrl"?: string;
        /**
          * Globale Opazität (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Point color for point geometries (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "pointColor"?: string;
        /**
          * Point radius for point geometries in pixels
          * @default 6
         */
        "pointRadius"?: number;
        /**
          * Stroke color for lines and polygon outlines (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "strokeColor"?: string;
        /**
          * Stroke opacity (0-1)
          * @default 1
         */
        "strokeOpacity"?: number;
        /**
          * Stroke width in pixels
          * @default 2
         */
        "strokeWidth"?: number;
        /**
          * Text color for labels (CSS color value)
          * @default '#000000'
         */
        "textColor"?: string;
        /**
          * Text property name from feature properties to display as label
         */
        "textProperty"?: string;
        /**
          * Text size for labels in pixels
          * @default 12
         */
        "textSize"?: number;
        /**
          * URL, von der eine WKT-Geometrie geladen wird (alternativ zu `wkt`).
         */
        "url"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible": boolean;
        /**
          * WKT-Geometrie (z. B. "POINT(11.57 48.14)" oder "POLYGON((...))").
         */
        "wkt"?: string;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 1000
         */
        "zIndex": number;
    }
    /**
     * OGC WMS Layer
     */
    interface VMapLayerWms {
        /**
          * Bildformat des GetMap-Requests.
          * @default "image/png"
         */
        "format": string;
        /**
          * Kommagetrennte Layer-Namen (z. B. "topp:states").
         */
        "layers": string;
        /**
          * Globale Opazität des WMS-Layers (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * WMS-`STYLES` Parameter (kommagetrennt).
          * @default ""
         */
        "styles"?: string;
        /**
          * Tiled/geslicete Requests verwenden (falls Server unterstützt).
          * @default true
         */
        "tiled": boolean;
        /**
          * Transparente Kacheln anfordern.
          * @default true
         */
        "transparent": boolean;
        /**
          * Basis-URL des WMS-Dienstes (GetMap-Endpunkt ohne Query-Parameter).
         */
        "url": string;
        /**
          * Sichtbarkeit des WMS-Layers.
          * @default true
         */
        "visible": boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 10
         */
        "zIndex": number;
    }
    /**
     * XYZ Tile Layer
     */
    interface VMapLayerXyz {
        /**
          * Attributions-/Copyright-Text (HTML erlaubt).
         */
        "attributions"?: string;
        /**
          * Maximaler Zoomlevel, den der Tile-Server liefert.
          * @default 19
         */
        "maxZoom"?: number;
        /**
          * Opazität (0–1).
          * @default 1
         */
        "opacity": number;
        /**
          * Subdomains für parallele Tile-Anfragen (z. B. "a,b,c").
         */
        "subdomains"?: string;
        /**
          * Größe einer Kachel in Pixeln.
          * @default 256
         */
        "tileSize"?: number;
        /**
          * URL-Template für Kacheln, z. B. "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png".
         */
        "url": string;
        /**
          * Sichtbarkeit des XYZ-Layers.
          * @default true
         */
        "visible": boolean;
    }
    interface VMapLayercontrol {
        /**
          * ID der zu steuernden Karte (DOM-Element mit dieser id)
         */
        "for": string;
    }
    interface VMapLayergroup {
        /**
          * Fügt ein Kind-Layer zur Gruppe hinzu.
          * @param layer Layer-Element (Web Component)
         */
        "addLayer": (layerConfig: LayerConfig, layerElementId?: string) => Promise<string>;
        /**
          * Base map identifier for this layer group. When set, layers in this group will be treated as base map layers.
          * @default null
         */
        "basemapid": string | null;
        /**
          * Globale Opazität (0–1) für alle Kinder.
          * @default 1
         */
        "opacity": number;
        /**
          * Sichtbarkeit der gesamten Gruppe.
          * @default true
         */
        "visible": boolean;
    }
    interface VMapStyle {
        /**
          * Whether to automatically apply the style when loaded.
          * @default true
         */
        "autoApply": boolean;
        /**
          * Inline style content as string (alternative to src).
         */
        "content"?: string;
        /**
          * The styling format to parse (currently supports 'sld').
          * @default 'sld'
         */
        "format": StyleFormat;
        /**
          * Get the currently parsed style.
         */
        "getStyle": () => Promise<ResolvedStyle | undefined>;
        /**
          * Target layer IDs to apply this style to. If not specified, applies to all compatible layers.
         */
        "layerTargets"?: string;
        /**
          * The style source - can be a URL to fetch from or inline SLD/style content.
         */
        "src"?: string;
    }
}
export interface VMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapElement;
}
export interface VMapBuilderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapBuilderElement;
}
export interface VMapLayerGeotiffCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerGeotiffElement;
}
export interface VMapLayerGoogleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerGoogleElement;
}
export interface VMapLayerOsmCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerOsmElement;
}
export interface VMapLayerScatterplotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerScatterplotElement;
}
export interface VMapLayerTile3dCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerTile3dElement;
}
export interface VMapLayerWktCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerWktElement;
}
export interface VMapLayerWmsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerWmsElement;
}
export interface VMapLayerXyzCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapLayerXyzElement;
}
export interface VMapStyleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVMapStyleElement;
}
declare global {
    interface HTMLVMapElementEventMap {
        "mapProviderReady": MapProviderDetail;
    }
    interface HTMLVMapElement extends Components.VMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapElementEventMap>(type: K, listener: (this: HTMLVMapElement, ev: VMapCustomEvent<HTMLVMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapElementEventMap>(type: K, listener: (this: HTMLVMapElement, ev: VMapCustomEvent<HTMLVMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapElement: {
        prototype: HTMLVMapElement;
        new (): HTMLVMapElement;
    };
    interface HTMLVMapBuilderElementEventMap {
        "configReady": BuilderConfig;
        "configError": {
    message: string;
    errors?: string[];
  };
    }
    /**
     * A component that builds map configurations dynamically from JSON/YAML configuration scripts.
     */
    interface HTMLVMapBuilderElement extends Components.VMapBuilder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapBuilderElementEventMap>(type: K, listener: (this: HTMLVMapBuilderElement, ev: VMapBuilderCustomEvent<HTMLVMapBuilderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapBuilderElementEventMap>(type: K, listener: (this: HTMLVMapBuilderElement, ev: VMapBuilderCustomEvent<HTMLVMapBuilderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapBuilderElement: {
        prototype: HTMLVMapBuilderElement;
        new (): HTMLVMapBuilderElement;
    };
    interface HTMLVMapLayerGeojsonElement extends Components.VMapLayerGeojson, HTMLStencilElement {
    }
    var HTMLVMapLayerGeojsonElement: {
        prototype: HTMLVMapLayerGeojsonElement;
        new (): HTMLVMapLayerGeojsonElement;
    };
    interface HTMLVMapLayerGeotiffElementEventMap {
        "ready": void;
    }
    interface HTMLVMapLayerGeotiffElement extends Components.VMapLayerGeotiff, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerGeotiffElementEventMap>(type: K, listener: (this: HTMLVMapLayerGeotiffElement, ev: VMapLayerGeotiffCustomEvent<HTMLVMapLayerGeotiffElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerGeotiffElementEventMap>(type: K, listener: (this: HTMLVMapLayerGeotiffElement, ev: VMapLayerGeotiffCustomEvent<HTMLVMapLayerGeotiffElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerGeotiffElement: {
        prototype: HTMLVMapLayerGeotiffElement;
        new (): HTMLVMapLayerGeotiffElement;
    };
    interface HTMLVMapLayerGoogleElementEventMap {
        "ready": void;
    }
    /**
     * Google Maps Basemap Layer
     */
    interface HTMLVMapLayerGoogleElement extends Components.VMapLayerGoogle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerGoogleElementEventMap>(type: K, listener: (this: HTMLVMapLayerGoogleElement, ev: VMapLayerGoogleCustomEvent<HTMLVMapLayerGoogleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerGoogleElementEventMap>(type: K, listener: (this: HTMLVMapLayerGoogleElement, ev: VMapLayerGoogleCustomEvent<HTMLVMapLayerGoogleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerGoogleElement: {
        prototype: HTMLVMapLayerGoogleElement;
        new (): HTMLVMapLayerGoogleElement;
    };
    interface HTMLVMapLayerOsmElementEventMap {
        "ready": void;
    }
    interface HTMLVMapLayerOsmElement extends Components.VMapLayerOsm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerOsmElementEventMap>(type: K, listener: (this: HTMLVMapLayerOsmElement, ev: VMapLayerOsmCustomEvent<HTMLVMapLayerOsmElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerOsmElementEventMap>(type: K, listener: (this: HTMLVMapLayerOsmElement, ev: VMapLayerOsmCustomEvent<HTMLVMapLayerOsmElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerOsmElement: {
        prototype: HTMLVMapLayerOsmElement;
        new (): HTMLVMapLayerOsmElement;
    };
    interface HTMLVMapLayerScatterplotElementEventMap {
        "ready": void;
    }
    interface HTMLVMapLayerScatterplotElement extends Components.VMapLayerScatterplot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerScatterplotElementEventMap>(type: K, listener: (this: HTMLVMapLayerScatterplotElement, ev: VMapLayerScatterplotCustomEvent<HTMLVMapLayerScatterplotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerScatterplotElementEventMap>(type: K, listener: (this: HTMLVMapLayerScatterplotElement, ev: VMapLayerScatterplotCustomEvent<HTMLVMapLayerScatterplotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerScatterplotElement: {
        prototype: HTMLVMapLayerScatterplotElement;
        new (): HTMLVMapLayerScatterplotElement;
    };
    interface HTMLVMapLayerTerrainElement extends Components.VMapLayerTerrain, HTMLStencilElement {
    }
    var HTMLVMapLayerTerrainElement: {
        prototype: HTMLVMapLayerTerrainElement;
        new (): HTMLVMapLayerTerrainElement;
    };
    interface HTMLVMapLayerTile3dElementEventMap {
        "ready": void;
    }
    interface HTMLVMapLayerTile3dElement extends Components.VMapLayerTile3d, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerTile3dElementEventMap>(type: K, listener: (this: HTMLVMapLayerTile3dElement, ev: VMapLayerTile3dCustomEvent<HTMLVMapLayerTile3dElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerTile3dElementEventMap>(type: K, listener: (this: HTMLVMapLayerTile3dElement, ev: VMapLayerTile3dCustomEvent<HTMLVMapLayerTile3dElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerTile3dElement: {
        prototype: HTMLVMapLayerTile3dElement;
        new (): HTMLVMapLayerTile3dElement;
    };
    interface HTMLVMapLayerWcsElement extends Components.VMapLayerWcs, HTMLStencilElement {
    }
    var HTMLVMapLayerWcsElement: {
        prototype: HTMLVMapLayerWcsElement;
        new (): HTMLVMapLayerWcsElement;
    };
    interface HTMLVMapLayerWfsElement extends Components.VMapLayerWfs, HTMLStencilElement {
    }
    var HTMLVMapLayerWfsElement: {
        prototype: HTMLVMapLayerWfsElement;
        new (): HTMLVMapLayerWfsElement;
    };
    interface HTMLVMapLayerWktElementEventMap {
        "ready": void;
    }
    interface HTMLVMapLayerWktElement extends Components.VMapLayerWkt, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerWktElementEventMap>(type: K, listener: (this: HTMLVMapLayerWktElement, ev: VMapLayerWktCustomEvent<HTMLVMapLayerWktElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerWktElementEventMap>(type: K, listener: (this: HTMLVMapLayerWktElement, ev: VMapLayerWktCustomEvent<HTMLVMapLayerWktElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerWktElement: {
        prototype: HTMLVMapLayerWktElement;
        new (): HTMLVMapLayerWktElement;
    };
    interface HTMLVMapLayerWmsElementEventMap {
        "ready": void;
    }
    /**
     * OGC WMS Layer
     */
    interface HTMLVMapLayerWmsElement extends Components.VMapLayerWms, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerWmsElementEventMap>(type: K, listener: (this: HTMLVMapLayerWmsElement, ev: VMapLayerWmsCustomEvent<HTMLVMapLayerWmsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerWmsElementEventMap>(type: K, listener: (this: HTMLVMapLayerWmsElement, ev: VMapLayerWmsCustomEvent<HTMLVMapLayerWmsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerWmsElement: {
        prototype: HTMLVMapLayerWmsElement;
        new (): HTMLVMapLayerWmsElement;
    };
    interface HTMLVMapLayerXyzElementEventMap {
        "ready": void;
    }
    /**
     * XYZ Tile Layer
     */
    interface HTMLVMapLayerXyzElement extends Components.VMapLayerXyz, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapLayerXyzElementEventMap>(type: K, listener: (this: HTMLVMapLayerXyzElement, ev: VMapLayerXyzCustomEvent<HTMLVMapLayerXyzElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapLayerXyzElementEventMap>(type: K, listener: (this: HTMLVMapLayerXyzElement, ev: VMapLayerXyzCustomEvent<HTMLVMapLayerXyzElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapLayerXyzElement: {
        prototype: HTMLVMapLayerXyzElement;
        new (): HTMLVMapLayerXyzElement;
    };
    interface HTMLVMapLayercontrolElement extends Components.VMapLayercontrol, HTMLStencilElement {
    }
    var HTMLVMapLayercontrolElement: {
        prototype: HTMLVMapLayercontrolElement;
        new (): HTMLVMapLayercontrolElement;
    };
    interface HTMLVMapLayergroupElement extends Components.VMapLayergroup, HTMLStencilElement {
    }
    var HTMLVMapLayergroupElement: {
        prototype: HTMLVMapLayergroupElement;
        new (): HTMLVMapLayergroupElement;
    };
    interface HTMLVMapStyleElementEventMap {
        "styleReady": ResolvedStyle;
        "styleError": Error;
    }
    interface HTMLVMapStyleElement extends Components.VMapStyle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVMapStyleElementEventMap>(type: K, listener: (this: HTMLVMapStyleElement, ev: VMapStyleCustomEvent<HTMLVMapStyleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVMapStyleElementEventMap>(type: K, listener: (this: HTMLVMapStyleElement, ev: VMapStyleCustomEvent<HTMLVMapStyleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVMapStyleElement: {
        prototype: HTMLVMapStyleElement;
        new (): HTMLVMapStyleElement;
    };
    interface HTMLElementTagNameMap {
        "v-map": HTMLVMapElement;
        "v-map-builder": HTMLVMapBuilderElement;
        "v-map-layer-geojson": HTMLVMapLayerGeojsonElement;
        "v-map-layer-geotiff": HTMLVMapLayerGeotiffElement;
        "v-map-layer-google": HTMLVMapLayerGoogleElement;
        "v-map-layer-osm": HTMLVMapLayerOsmElement;
        "v-map-layer-scatterplot": HTMLVMapLayerScatterplotElement;
        "v-map-layer-terrain": HTMLVMapLayerTerrainElement;
        "v-map-layer-tile3d": HTMLVMapLayerTile3dElement;
        "v-map-layer-wcs": HTMLVMapLayerWcsElement;
        "v-map-layer-wfs": HTMLVMapLayerWfsElement;
        "v-map-layer-wkt": HTMLVMapLayerWktElement;
        "v-map-layer-wms": HTMLVMapLayerWmsElement;
        "v-map-layer-xyz": HTMLVMapLayerXyzElement;
        "v-map-layercontrol": HTMLVMapLayercontrolElement;
        "v-map-layergroup": HTMLVMapLayergroupElement;
        "v-map-style": HTMLVMapStyleElement;
    }
}
declare namespace LocalJSX {
    interface VMap {
        /**
          * Mittelpunkt der Karte im **WGS84**-Koordinatensystem. Erwartet [lon, lat] (Längengrad, Breitengrad).
          * @default [0, 0]
          * @example <v-map center="[11.5761, 48.1371]" zoom="12"></v-map>
         */
        "center"?: string;
        /**
          * Aktiviert ein „CSS-Only“-Rendering (z. B. für einfache Tests/Layouts). Bei `true` werden keine Provider initialisiert.
          * @default false
         */
        "cssMode"?: CssMode;
        /**
          * Zu verwendender Karten-Provider. Unterstützte Werte: "ol" | "leaflet" | "cesium" | "deck".
          * @default "ol"
          * @example <v-map flavour="leaflet"></v-map>
         */
        "flavour"?: Flavour;
        /**
          * Wird ausgelöst, sobald der Karten-Provider initialisiert wurde und Layers entgegennimmt. `detail` enthält `{ provider, flavour }`.
          * @event mapProviderReady
         */
        "onMapProviderReady"?: (event: VMapCustomEvent<MapProviderDetail>) => void;
        /**
          * Falls true, injiziert v-map automatisch die Import-Map.
          * @default true
         */
        "useDefaultImportMap"?: boolean;
        /**
          * Anfangs-Zoomstufe. Skala abhängig vom Provider (typisch 0–20).
          * @default 3
         */
        "zoom"?: number;
    }
    /**
     * A component that builds map configurations dynamically from JSON/YAML configuration scripts.
     */
    interface VMapBuilder {
        /**
          * Configuration object for the map builder. Can be any structure that will be normalized to BuilderConfig.
         */
        "mapconfig"?: unknown;
        /**
          * Event emitted when there is an error parsing the map configuration.
         */
        "onConfigError"?: (event: VMapBuilderCustomEvent<{
    message: string;
    errors?: string[];
  }>) => void;
        /**
          * Event emitted when the map configuration has been successfully parsed and is ready to use.
         */
        "onConfigReady"?: (event: VMapBuilderCustomEvent<BuilderConfig>) => void;
    }
    interface VMapLayerGeojson {
        /**
          * Fill color for polygon geometries (CSS color value)
          * @default 'rgba(0,100,255,0.3)'
         */
        "fillColor"?: string;
        /**
          * Fill opacity for polygon geometries (0-1)
          * @default 0.3
         */
        "fillOpacity"?: number;
        /**
          * Prop, die du intern nutzt/weiterverarbeitest
         */
        "geojson"?: unknown;
        /**
          * Icon size as [width, height] in pixels (comma-separated string like "32,32")
          * @default "32,32"
         */
        "iconSize"?: string;
        /**
          * Icon URL for point features (alternative to pointColor/pointRadius)
         */
        "iconUrl"?: string;
        /**
          * Opazität der geojson-Kacheln (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Point color for point geometries (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "pointColor"?: string;
        /**
          * Point radius for point geometries in pixels
          * @default 6
         */
        "pointRadius"?: number;
        /**
          * Stroke color for lines and polygon outlines (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "strokeColor"?: string;
        /**
          * Stroke opacity (0-1)
          * @default 1
         */
        "strokeOpacity"?: number;
        /**
          * Stroke width in pixels
          * @default 2
         */
        "strokeWidth"?: number;
        /**
          * Text color for labels (CSS color value)
          * @default '#000000'
         */
        "textColor"?: string;
        /**
          * Text property name from feature properties to display as label
         */
        "textProperty"?: string;
        /**
          * Text size for labels in pixels
          * @default 12
         */
        "textSize"?: number;
        /**
          * URL to fetch GeoJSON data from. Alternative to providing data via slot.
          * @default null
         */
        "url"?: string;
        /**
          * Whether the layer is visible on the map.
          * @default true
         */
        "visible"?: boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 1000
         */
        "zIndex"?: number;
    }
    interface VMapLayerGeotiff {
        /**
          * Wird ausgelöst, wenn der GeoTIFF-Layer bereit ist.
          * @event ready
         */
        "onReady"?: (event: VMapLayerGeotiffCustomEvent<void>) => void;
        /**
          * Opazität der GeoTIFF-Kacheln (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * URL to the GeoTIFF file to be displayed on the map.
          * @default null
         */
        "url"?: string;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible"?: boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 1000
         */
        "zIndex"?: number;
    }
    /**
     * Google Maps Basemap Layer
     */
    interface VMapLayerGoogle {
        /**
          * Google Maps API-Schlüssel.
          * @example <v-map-layer-google api-key="YOUR_KEY"></v-map-layer-google>
         */
        "apiKey"?: string;
        /**
          * Sprach-Lokalisierung (BCP-47, z. B. "de", "en-US").
          * @default "en"
         */
        "language"?: string;
        /**
          * Google Maps libraries to load (comma-separated string).
          * @example "geometry,places,drawing"
         */
        "libraries"?: string;
        /**
          * Karten-Typ: "roadmap" | "satellite" | "hybrid" | "terrain".
          * @default "roadmap"
         */
        "mapType"?: | 'roadmap'
    | 'satellite'
    | 'terrain'
    | 'hybrid';
        /**
          * Maximum zoom level for the layer.
         */
        "maxZoom"?: number;
        /**
          * Signalisiert, dass der Google-Layer bereit ist. `detail` enthält Metadaten.
          * @event ready
         */
        "onReady"?: (event: VMapLayerGoogleCustomEvent<void>) => void;
        /**
          * Opazität des Layers (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Region-Bias (ccTLD/Region-Code, z. B. "DE", "US"). Beeinflusst Labels/Suchergebnisse.
         */
        "region"?: string;
        /**
          * Scale factor for tile display.
          * @default "scaleFactor1x"
         */
        "scale"?: 'scaleFactor1x' | 'scaleFactor2x' | 'scaleFactor4x';
        /**
          * Custom styles for the Google Map (JSON array of styling objects). Can be passed as JSON string or array.
         */
        "styles"?: any[] | string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible"?: boolean;
    }
    interface VMapLayerOsm {
        /**
          * Wird ausgelöst, wenn der OSM-Layer bereit ist.
          * @event ready
         */
        "onReady"?: (event: VMapLayerOsmCustomEvent<void>) => void;
        /**
          * Opazität der OSM-Kacheln (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Base URL for OpenStreetMap tile server. Defaults to the standard OSM tile server.
          * @default 'https://tile.openstreetmap.org'
         */
        "url"?: string;
        /**
          * Sichtbarkeit des Layers
          * @default true
         */
        "visible"?: boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 10
         */
        "zIndex"?: number;
    }
    interface VMapLayerScatterplot {
        /**
          * Datenquelle für Punkte. Erwartet Objekte mit mindestens einer Position in [lon, lat]. Zusätzliche Felder sind erlaubt.
         */
        "data"?: string;
        /**
          * Funktion zur Bestimmung der Füllfarbe je Punkt. Rückgabe z. B. [r,g,b] oder CSS-Farbe (providerabhängig).
          * @default '#3388ff'
         */
        "getFillColor"?: Color;
        /**
          * Funktion/konstanter Wert für den Punkt-Radius.
          * @default 4
         */
        "getRadius"?: number;
        /**
          * Wird ausgelöst, sobald der Scatterplot registriert wurde.
          * @event ready
         */
        "onReady"?: (event: VMapLayerScatterplotCustomEvent<void>) => void;
        /**
          * Globale Opazität (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Optionaler Remote-Pfad für JSON/CSV/GeoJSON, der zu `data` geladen wird.
         */
        "url"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible"?: boolean;
    }
    interface VMapLayerTerrain {
        /**
          * Basisfarbe für das Terrain. Erwartet Hex oder RGB (z. B. '#ff0000' oder '255,0,0').
         */
        "color"?: string;
        /**
          * URL zu Höhenraster im Heightmap-Format (z. B. GeoTIFF oder PNG Heightmap).
         */
        "elevationData": string;
        /**
          * JSON-Repräsentation eines Elevation-Decoders (z. B. '{"r":1,"g":1,"b":1,"offset":0}').
         */
        "elevationDecoder"?: string;
        /**
          * Maximale Zoomstufe für das Terrain.
         */
        "maxZoom"?: number;
        /**
          * Fehler-Toleranz für das Mesh (wird an TerrainRenderer durchgereicht).
         */
        "meshMaxError"?: number;
        /**
          * Minimale Zoomstufe für das Terrain.
         */
        "minZoom"?: number;
        /**
          * Opazität des Layers.
          * @default 1
         */
        "opacity"?: number;
        /**
          * Optionale Textur (RGB) für das Terrain.
         */
        "texture"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible"?: boolean;
        /**
          * Darstellung des Mesh als Drahtgitter.
         */
        "wireframe"?: boolean;
        /**
          * Z-Index für die Darstellung.
          * @default 1000
         */
        "zIndex"?: number;
    }
    interface VMapLayerTile3d {
        /**
          * Fired once the tileset layer is initialised.
         */
        "onReady"?: (event: VMapLayerTile3dCustomEvent<void>) => void;
        /**
          * Global opacity factor (0-1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Optional JSON string or object with Cesium3DTileset options.
         */
        "tilesetOptions"?: string | Record<string, unknown>;
        /**
          * URL pointing to the Cesium 3D Tileset.
         */
        "url": string;
        /**
          * Whether the tileset should be visible.
          * @default true
         */
        "visible"?: boolean;
        /**
          * Z-index used for ordering tilesets.
          * @default 1000
         */
        "zIndex"?: number;
    }
    interface VMapLayerWcs {
        /**
          * Coverage-Name/ID.
         */
        "coverageName": string;
        /**
          * Ausgabeformat, z. B. image/tiff.
          * @default 'image/tiff'
         */
        "format"?: string;
        /**
          * Opazität (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Zusätzliche Parameter als JSON-String.
         */
        "params"?: string;
        /**
          * Projektion (Projection) für die Quelle.
         */
        "projection"?: string;
        /**
          * Auflösungen als JSON-Array, z. B. [1000,500].
         */
        "resolutions"?: string;
        /**
          * Basis-URL des WCS-Dienstes.
         */
        "url": string;
        /**
          * WCS-Version.
          * @default '1.1.0'
         */
        "version"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible"?: boolean;
        /**
          * Z-Index für die Darstellung.
          * @default 1000
         */
        "zIndex"?: number;
    }
    interface VMapLayerWfs {
        /**
          * Opazität (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Ausgabeformat, z. B. application/json.
          * @default 'application/json'
         */
        "outputFormat"?: string;
        /**
          * Zusätzliche Parameter als JSON-String.
         */
        "params"?: string;
        /**
          * Ziel-Referenzsystem, Standard EPSG:3857.
          * @default 'EPSG:3857'
         */
        "srsName"?: string;
        /**
          * Feature-Typ (typeName) des WFS.
         */
        "typeName": string;
        /**
          * WFS Endpunkt (z. B. https://server/wfs).
         */
        "url": string;
        /**
          * WFS Version, Standard 1.1.0.
          * @default '1.1.0'
         */
        "version"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible"?: boolean;
        /**
          * Z-Index für Rendering.
          * @default 1000
         */
        "zIndex"?: number;
    }
    interface VMapLayerWkt {
        /**
          * Fill color for polygon geometries (CSS color value)
          * @default 'rgba(0,100,255,0.3)'
         */
        "fillColor"?: string;
        /**
          * Fill opacity for polygon geometries (0-1)
          * @default 0.3
         */
        "fillOpacity"?: number;
        /**
          * Icon size as [width, height] in pixels (comma-separated string like "32,32")
          * @default "32,32"
         */
        "iconSize"?: string;
        /**
          * Icon URL for point features (alternative to pointColor/pointRadius)
         */
        "iconUrl"?: string;
        /**
          * Signalisiert, dass das WKT-Layer initialisiert ist.
          * @event ready
         */
        "onReady"?: (event: VMapLayerWktCustomEvent<void>) => void;
        /**
          * Globale Opazität (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Point color for point geometries (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "pointColor"?: string;
        /**
          * Point radius for point geometries in pixels
          * @default 6
         */
        "pointRadius"?: number;
        /**
          * Stroke color for lines and polygon outlines (CSS color value)
          * @default 'rgba(0,100,255,1)'
         */
        "strokeColor"?: string;
        /**
          * Stroke opacity (0-1)
          * @default 1
         */
        "strokeOpacity"?: number;
        /**
          * Stroke width in pixels
          * @default 2
         */
        "strokeWidth"?: number;
        /**
          * Text color for labels (CSS color value)
          * @default '#000000'
         */
        "textColor"?: string;
        /**
          * Text property name from feature properties to display as label
         */
        "textProperty"?: string;
        /**
          * Text size for labels in pixels
          * @default 12
         */
        "textSize"?: number;
        /**
          * URL, von der eine WKT-Geometrie geladen wird (alternativ zu `wkt`).
         */
        "url"?: string;
        /**
          * Sichtbarkeit des Layers.
          * @default true
         */
        "visible"?: boolean;
        /**
          * WKT-Geometrie (z. B. "POINT(11.57 48.14)" oder "POLYGON((...))").
         */
        "wkt"?: string;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 1000
         */
        "zIndex"?: number;
    }
    /**
     * OGC WMS Layer
     */
    interface VMapLayerWms {
        /**
          * Bildformat des GetMap-Requests.
          * @default "image/png"
         */
        "format"?: string;
        /**
          * Kommagetrennte Layer-Namen (z. B. "topp:states").
         */
        "layers": string;
        /**
          * Signalisiert, dass der WMS-Layer bereit ist.
          * @event ready
         */
        "onReady"?: (event: VMapLayerWmsCustomEvent<void>) => void;
        /**
          * Globale Opazität des WMS-Layers (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * WMS-`STYLES` Parameter (kommagetrennt).
          * @default ""
         */
        "styles"?: string;
        /**
          * Tiled/geslicete Requests verwenden (falls Server unterstützt).
          * @default true
         */
        "tiled"?: boolean;
        /**
          * Transparente Kacheln anfordern.
          * @default true
         */
        "transparent"?: boolean;
        /**
          * Basis-URL des WMS-Dienstes (GetMap-Endpunkt ohne Query-Parameter).
         */
        "url": string;
        /**
          * Sichtbarkeit des WMS-Layers.
          * @default true
         */
        "visible"?: boolean;
        /**
          * Z-index for layer stacking order. Higher values render on top.
          * @default 10
         */
        "zIndex"?: number;
    }
    /**
     * XYZ Tile Layer
     */
    interface VMapLayerXyz {
        /**
          * Attributions-/Copyright-Text (HTML erlaubt).
         */
        "attributions"?: string;
        /**
          * Maximaler Zoomlevel, den der Tile-Server liefert.
          * @default 19
         */
        "maxZoom"?: number;
        /**
          * Wird ausgelöst, wenn der XYZ-Layer bereit ist.
          * @event ready
         */
        "onReady"?: (event: VMapLayerXyzCustomEvent<void>) => void;
        /**
          * Opazität (0–1).
          * @default 1
         */
        "opacity"?: number;
        /**
          * Subdomains für parallele Tile-Anfragen (z. B. "a,b,c").
         */
        "subdomains"?: string;
        /**
          * Größe einer Kachel in Pixeln.
          * @default 256
         */
        "tileSize"?: number;
        /**
          * URL-Template für Kacheln, z. B. "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png".
         */
        "url": string;
        /**
          * Sichtbarkeit des XYZ-Layers.
          * @default true
         */
        "visible"?: boolean;
    }
    interface VMapLayercontrol {
        /**
          * ID der zu steuernden Karte (DOM-Element mit dieser id)
         */
        "for"?: string;
    }
    interface VMapLayergroup {
        /**
          * Base map identifier for this layer group. When set, layers in this group will be treated as base map layers.
          * @default null
         */
        "basemapid"?: string | null;
        /**
          * Globale Opazität (0–1) für alle Kinder.
          * @default 1
         */
        "opacity"?: number;
        /**
          * Sichtbarkeit der gesamten Gruppe.
          * @default true
         */
        "visible"?: boolean;
    }
    interface VMapStyle {
        /**
          * Whether to automatically apply the style when loaded.
          * @default true
         */
        "autoApply"?: boolean;
        /**
          * Inline style content as string (alternative to src).
         */
        "content"?: string;
        /**
          * The styling format to parse (currently supports 'sld').
          * @default 'sld'
         */
        "format"?: StyleFormat;
        /**
          * Target layer IDs to apply this style to. If not specified, applies to all compatible layers.
         */
        "layerTargets"?: string;
        /**
          * Fired when style parsing fails.
         */
        "onStyleError"?: (event: VMapStyleCustomEvent<Error>) => void;
        /**
          * Fired when style is successfully parsed and ready to apply.
         */
        "onStyleReady"?: (event: VMapStyleCustomEvent<ResolvedStyle>) => void;
        /**
          * The style source - can be a URL to fetch from or inline SLD/style content.
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "v-map": VMap;
        "v-map-builder": VMapBuilder;
        "v-map-layer-geojson": VMapLayerGeojson;
        "v-map-layer-geotiff": VMapLayerGeotiff;
        "v-map-layer-google": VMapLayerGoogle;
        "v-map-layer-osm": VMapLayerOsm;
        "v-map-layer-scatterplot": VMapLayerScatterplot;
        "v-map-layer-terrain": VMapLayerTerrain;
        "v-map-layer-tile3d": VMapLayerTile3d;
        "v-map-layer-wcs": VMapLayerWcs;
        "v-map-layer-wfs": VMapLayerWfs;
        "v-map-layer-wkt": VMapLayerWkt;
        "v-map-layer-wms": VMapLayerWms;
        "v-map-layer-xyz": VMapLayerXyz;
        "v-map-layercontrol": VMapLayercontrol;
        "v-map-layergroup": VMapLayergroup;
        "v-map-style": VMapStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v-map": LocalJSX.VMap & JSXBase.HTMLAttributes<HTMLVMapElement>;
            /**
             * A component that builds map configurations dynamically from JSON/YAML configuration scripts.
             */
            "v-map-builder": LocalJSX.VMapBuilder & JSXBase.HTMLAttributes<HTMLVMapBuilderElement>;
            "v-map-layer-geojson": LocalJSX.VMapLayerGeojson & JSXBase.HTMLAttributes<HTMLVMapLayerGeojsonElement>;
            "v-map-layer-geotiff": LocalJSX.VMapLayerGeotiff & JSXBase.HTMLAttributes<HTMLVMapLayerGeotiffElement>;
            /**
             * Google Maps Basemap Layer
             */
            "v-map-layer-google": LocalJSX.VMapLayerGoogle & JSXBase.HTMLAttributes<HTMLVMapLayerGoogleElement>;
            "v-map-layer-osm": LocalJSX.VMapLayerOsm & JSXBase.HTMLAttributes<HTMLVMapLayerOsmElement>;
            "v-map-layer-scatterplot": LocalJSX.VMapLayerScatterplot & JSXBase.HTMLAttributes<HTMLVMapLayerScatterplotElement>;
            "v-map-layer-terrain": LocalJSX.VMapLayerTerrain & JSXBase.HTMLAttributes<HTMLVMapLayerTerrainElement>;
            "v-map-layer-tile3d": LocalJSX.VMapLayerTile3d & JSXBase.HTMLAttributes<HTMLVMapLayerTile3dElement>;
            "v-map-layer-wcs": LocalJSX.VMapLayerWcs & JSXBase.HTMLAttributes<HTMLVMapLayerWcsElement>;
            "v-map-layer-wfs": LocalJSX.VMapLayerWfs & JSXBase.HTMLAttributes<HTMLVMapLayerWfsElement>;
            "v-map-layer-wkt": LocalJSX.VMapLayerWkt & JSXBase.HTMLAttributes<HTMLVMapLayerWktElement>;
            /**
             * OGC WMS Layer
             */
            "v-map-layer-wms": LocalJSX.VMapLayerWms & JSXBase.HTMLAttributes<HTMLVMapLayerWmsElement>;
            /**
             * XYZ Tile Layer
             */
            "v-map-layer-xyz": LocalJSX.VMapLayerXyz & JSXBase.HTMLAttributes<HTMLVMapLayerXyzElement>;
            "v-map-layercontrol": LocalJSX.VMapLayercontrol & JSXBase.HTMLAttributes<HTMLVMapLayercontrolElement>;
            "v-map-layergroup": LocalJSX.VMapLayergroup & JSXBase.HTMLAttributes<HTMLVMapLayergroupElement>;
            "v-map-style": LocalJSX.VMapStyle & JSXBase.HTMLAttributes<HTMLVMapStyleElement>;
        }
    }
}
